import { ProjectMetrics, PortfolioData } from "./types";

export const defaultPortfolioData: PortfolioData = {
  hero: {
    title: "Hi! I'm Samyukth Dharmarajan.",
    subtitle: "ASSOCIATE SOFTWARE ENGINEER",
    description: "24 year old associate software engineer passionate about Frontend engineering from India.",
  },
  milestones: [
    {
      year: "Aug 2024 – Present",
      title: "Associate Software Engineer",
      company: "Terawe Corporation (Microsoft Vendor)",
      desc: "Architected reusable React.js/TypeScript component library using atomic design. Resolved client-side bottlenecks on 50,000-item payloads. Engineered WCAG 2.1 AA accessibility standards.",
      iconType: "work",
      imagePath: "/images/terawe_logo.png",
      subMilestones: [
        {
          year: "March 2026",
          title: "WCAG 2.1 AA Accessibility",
          company: "Terawe Corp",
          desc: "Engineered full screen reader and keyboard navigability, reducing user support tickets by 15%.",
          type: "other",
        },
        {
          year: "Jan 2026",
          title: "CI/CD & Testing Automated Dual-Layer Pipeline",
          company: "Terawe Corp",
          desc: "Combined Jest unit testing (85% coverage) with Playwright E2E automation, cutting production regressions by 30%.",
          type: "other",
        },
        {
          year: "April 2025",
          title: "50k JSON DOM Virtualization",
          company: "Terawe Corp",
          desc: "Optimized dataset rendering using windowing and useMemo, restoring frame rates from 12 FPS to a stable 60 FPS.",
          type: "other",
        },
        {
          year: "Nov 2024",
          title: "Atomic Design Library",
          company: "Terawe Corp",
          desc: "Unified UI architecture across 3 internal product teams, accelerating feature delivery by 20%.",
          type: "other",
        },
      ],
    },
    {
      year: "Sept 2024",
      title:
        "Certification: Microsoft Certified: Azure Administrator Associate (AZ-104)",
      company: "Microsoft Certification",
      desc: "Achieved AZ-104 certification for managing cloud resources, storage, virtual networks, and CI/CD integrations.",
      iconType: "certification",
      imagePath: "/images/az-104.png",
    },
    {
      year: "June 2020 – July 2024",
      title: "B.Tech in Computer Science",
      company: "APJ Abdul Kalam Technological University",
      desc: "Graduated with honors in Computer Science from Kochi, India, securing a CGPA of 7.46/10.",
      iconType: "education",
      imagePath: "/images/ktu_logo.jpg",
      subMilestones: [
        {
          year: "April 2023 – June 2023",
          title: "Web Development Intern",
          company: "Acmegrade",
          desc: "Built responsive user interfaces using React. Implemented state management with Redux Toolkit. Developed backend systems using Node.js and MongoDB.",
          type: "internship",
        },
      ],
    },
  ],
  projects: [],
};

export const projectsData: ProjectMetrics[] = [
  {
    id: "stackpilot",
    title: "StackPilot",
    description: "StackPilot is an intelligent career transition and developer resource planning platform designed to parse uploaded resumes, track compatibility scores, and suggest relevant high-matching software job roles. Integrated generative AI for real-time PDF parsing, client-side skill profiling, and optimistic UI streaming. Automated Vercel deployments via GitHub Actions.",
    customerDetails: "Open Source / Developer Tooling",
    techStack: ["NestJS", "React 19", "Next.js 16", "Zustand", "TanStack Query", "Radix UI", "SQLite", "Prisma ORM", "OAuth 2.0", "Tailwind CSS", "TypeScript"],
    liveLink: "https://stackpilot-jext.onrender.com/",
    statusTag: "Development",
    projectType: "personal",
    screenshotPath: "/images/stackpilot_landing.png",
    performance: { users: "500+", concurrency: "50+", uptime: "99.9%" },
    sourceLink: "https://github.com/samyukthdraj/StackPilot",
  },
  {
    id: "friends-portfolio",
    title: "Friend's Portfolio Website",
    description: "A modern, responsive personal portfolio website built to showcase projects and resume details dynamically.",
    customerDetails: "Personal",
    techStack: ["Next.js", "React", "Tailwind CSS"],
    liveLink: "https://neha-sreejith.vercel.app/",
    statusTag: "Live",
    projectType: "personal",
    screenshotPath: "/images/friend's_portfolio.png",
    performance: {},
    sourceLink: "https://github.com/samyukthdraj/media-app",
  },
  {
    id: "manpower-supply",
    title: "Manpower Supply Application",
    description: "A robust manpower supply web application built with administrator access to manage workers and deployments.",
    customerDetails: "HAAD Technical Services",
    techStack: ["Next.js", "React", "Tailwind CSS"],
    liveLink: "https://haadtechnicalservicescollc.vercel.app/",
    statusTag: "Live",
    projectType: "personal",
    screenshotPath: "/images/manpower_landing.png",
    performance: {},
    sourceLink: "https://github.com/samyukthdraj/HAADTECHNICALSERVICES/tree/main",
  },
  {
    id: "expense-tracker",
    title: "Expense Tracker",
    description: "A comprehensive full-stack expense tracking application designed to help users manage, visualize, and track their personal financial data and budgets.",
    customerDetails: "Personal",
    techStack: ["React", "Node.js", "Express", "MongoDB", "Tailwind CSS"],
    liveLink: "https://expense-tracker-odh7.onrender.com/expenses",
    statusTag: "Live",
    projectType: "personal",
    screenshotPath: "/images/expense_tracker_landing_cropped.png",
    performance: {},
    sourceLink: "https://github.com/samyukthdraj/Expense-Tracker",
  },
  {
    id: "skillup2",
    title: "SkillUp 2.0",
    description: "SkillUp 2.0 is an enterprise-grade Gen AI educational learning management platform configured with 5 distinct user personas. Built to support robust certification path tracking, it integrates secure Credly badge verifications and detailed progress visualization dashboards.",
    customerDetails: "Vollee AI Internal / Consumer",
    techStack: ["Next.js 14", "React 18", "Redux Toolkit", "Ant Design", "Recharts", "OpenAI GPT-4o", "PostgreSQL", "Prisma ORM", "OAuth 2.0", "Tailwind CSS", "TypeScript"],
    liveLink: "https://skillup.vollee.ai",
    statusTag: "Live",
    projectType: "enterprise",
    screenshotPath: "/images/skillup_2.0_landing.png",
    performance: { users: "10k+", concurrency: "1.2k", uptime: "99.9%" },
  },
  {
    id: "skillupEdis",
    title: "Ignite EdIs C2k",
    description: "Ignite EdIs C2k is an enterprise learning management and licensing platform engineered for the Education Authority of Northern Ireland. Built to manage mandatory compliance and teacher certification, the platform features a custom checkpoint-gated Vidstack player. Orchestrated high-availability HLS media streaming via Azure Front Door CDN, absorbing 24,000+ concurrent users with zero buffering.",
    customerDetails: "Education Authority of Northern Ireland",
    techStack: ["React 19", "Next.js 16", "Vidstack Player", "Azure Web Apps", "Azure Redis", "SQL Server", "OAuth 2.0 / SAML SSO", "Azure AD MFA", "Tailwind CSS v4", "TypeScript"],
    liveLink: "https://skillup-edis.azurewebsites.net/",
    statusTag: "Live",
    projectType: "enterprise",
    screenshotPath: "/images/ignite_edis_c2k_landing.png",
    performance: { users: "24k", concurrency: "5k", uptime: "99.95%" },
  },
  {
    id: "unified-dashboard",
    title: "Unified Dashboard",
    description: "Developed a real-time, responsive enterprise dashboard using Azure DevOps APIs to ingest live metrics for 500+ internal users. Designed global state architecture for 50,000+ item payloads using Redux Toolkit with container-level memoization, eliminating unnecessary re-renders.",
    customerDetails: "Enterprise Tool",
    techStack: ["Next.js", "TypeScript", "Redux Toolkit", "Azure DevOps APIs"],
    liveLink: "",
    statusTag: "Live",
    projectType: "enterprise",
    screenshotPath: "/images/unified_dashboard_landing.png",
    performance: { users: "500+", concurrency: "N/A", uptime: "99.9%" },
  }
];

defaultPortfolioData.projects = projectsData;
