import { ProjectMetrics } from "./types";

export const projectsData: ProjectMetrics[] = [
  {
    id: "stackpilot",
    title: "StackPilot",
    description: "StackPilot is an intelligent career transition and developer resource planning platform designed to parse uploaded resumes, track compatibility scores, and suggest relevant high-matching software job roles.",
    customerDetails: "Open Source / Developer Tooling",
    techStack: ["NestJS", "React 19", "Next.js 16", "Zustand", "TanStack Query", "Radix UI", "SQLite", "Prisma ORM", "OAuth 2.0", "Tailwind CSS", "TypeScript"],
    liveLink: "https://stackpilot-jext.onrender.com/",
    statusTag: "Development",
    projectType: "personal",
    screenshotPath: "/images/stackpilot_landing.png",
    performance: { users: "500+", concurrency: "50+", uptime: "99.9%" },
    sourceLink: "https://github.com/samyukthdraj/StackPilot",
  },
  {
    id: "friends-portfolio",
    title: "Friend's Portfolio Website",
    description: "A modern, responsive personal portfolio website built to showcase projects and resume details dynamically.",
    customerDetails: "Personal",
    techStack: ["Next.js", "React", "Tailwind CSS"],
    liveLink: "https://neha-sreejith.vercel.app/",
    statusTag: "Live",
    projectType: "personal",
    screenshotPath: "/images/friend's_portfolio.png",
    performance: {},
    sourceLink: "https://github.com/samyukthdraj/media-app",
  },
  {
    id: "manpower-supply",
    title: "Manpower Supply Application",
    description: "A robust manpower supply web application built with administrator access to manage workers and deployments.",
    customerDetails: "HAAD Technical Services",
    techStack: ["Next.js", "React", "Tailwind CSS"],
    liveLink: "https://haadtechnicalservicescollc.vercel.app/",
    statusTag: "Live",
    projectType: "personal",
    screenshotPath: "/images/manpower_landing.png",
    performance: {},
    sourceLink: "https://github.com/samyukthdraj/HAADTECHNICALSERVICES/tree/main",
  },
  {
    id: "skillup2",
    title: "SkillUp 2.0",
    description: "SkillUp 2.0 is an enterprise-grade Gen AI educational learning management platform configured with 5 distinct user personas. Built to support robust certification path tracking, it integrates secure Credly badge verifications and detailed progress visualization dashboards.",
    customerDetails: "Vollee AI Internal / Consumer",
    techStack: ["Next.js 14", "React 18", "Redux Toolkit", "Ant Design", "Recharts", "OpenAI GPT-4o", "PostgreSQL", "Prisma ORM", "OAuth 2.0", "Tailwind CSS", "TypeScript"],
    liveLink: "https://skillup.vollee.ai",
    statusTag: "Live",
    projectType: "enterprise",
    screenshotPath: "/images/skillup_2.0_landing.png",
    performance: { users: "10k+", concurrency: "1.2k", uptime: "99.9%" },
  },
  {
    id: "skillupEdis",
    title: "Ignite EdIs C2k",
    description: "Ignite EdIs C2k is an enterprise learning management and licensing platform engineered for the Education Authority of Northern Ireland. Built to manage mandatory compliance and teacher certification, the platform features a custom checkpoint-gated Vidstack player.",
    customerDetails: "Education Authority of Northern Ireland",
    techStack: ["React 19", "Next.js 16", "Vidstack Player", "Azure Web Apps", "Azure Redis", "SQL Server", "OAuth 2.0 / SAML SSO", "Azure AD MFA", "Tailwind CSS v4", "TypeScript"],
    liveLink: "https://skillup-edis.azurewebsites.net/",
    statusTag: "Live",
    projectType: "enterprise",
    screenshotPath: "/images/ignite_edis_c2k_landing.png",
    performance: { users: "24k", concurrency: "5k", uptime: "99.95%" },
  }
];
